all:
  hosts:
    example:

  vars:
    ansible_connection: ansible.netcommon.network_cli
    # https://github.com/ansible-collections/vyos.vyos/pull/69#issuecomment-659679842
    ansible_network_os: vyos.vyos.vyos
    ansible_command_timeout: 180
    ansible_host_key_checking: false

    v4:
      example_net: "192.168.50.0/23"
      example_vpn: "192.168.52.0/23"
      example:
        vyos: "192.168.50.0"
        app1: "192.168.50.3"
        app2: "192.168.50.5"
        app3: "192.168.50.7"
        mgnt: "192.168.50.9"

      external_net: "172.20.0.0/16"
      external_vpn: "172.20.20.0/24"
      external:
        vyos: "172.20.0.1"
        ctrl: "172.20.0.2"
        exam: "172.20.0.3"
        test: "172.20.0.4"
        mgnt: "172.20.0.5"

    v6:
      example_net: "fd00:0:0:1::/64"
      example_vpn: "fd00:0:0:2::/64"
      example:
        vyos:
          host: "fd00:0:0:3:c0d0:639a:c18d:1234"
        app1:
          host: "fd00:0:0:3:c0d0:639a:c18d:bf1c"
          adr1: "fd00:0:0:3:c0d0:639a:c18d:bf1d"
          adr2: "fd00:0:0:3:c0d0:639a:c18d:bf1e"
          adr3: "fd00:0:0:3:c0d0:639a:c18d:bf1f"
        app2:
          host: "fd00:0:0:3:53af:9e9d:dc98:b06a"
          apps: "fd00:0:0:3:53af:9e9d:dc98:b06b"
        app3:
          host: "fd00:0:0:3:1d96:202c:9b2d:383c"
          chat: "fd00:0:0:3:1d96:202c:9b2d:383d"
        mgnt:
          host: "fd00:0:0:3:544f:64d4:eac6:f83a"

      external_net: "fd00:0:0:3::/64"
      external_vpn: "fd00:0:0:4::/64"
      external:
        vyos:
          host: "fd00:0:0:3::"
        ctrl:
          host: "fd00:0:0:3::1"
        exam:
          host: "fd00:0:0:3::2"
        test:
          host: "fd00:0:0:3::3"
        mgnt:
          host: "fd00:0:0:3::4"
