---
- name: Merge the provided configuration with the existing running configuration
  vyos.vyos.vyos_firewall_global:
    state: merged
    config:
      group:
        network_group:
          - name: "NET-PRIVATE-6"
            afi: ipv6
            description: "ipv6 bogon prefixes: Example for secshellnet/ansible-vyos-validator"
            members:
              - address: "fc00::/7"
              - address: "::/8"
              - address: "0100::/64"
              - address: "2001:2::/48"
              - address: "2001:10::/28"
              - address: "2001:db8::/32"
              - address: "2002::/16"
              - address: "3ffe::/16"
              - address: "fe80::/10"
              - address: "fec0::/10"
              - address: "ff00::/8"
