---
- name: "Configure local firewall ruleset (ipv4)"
  vyos.vyos.vyos_firewall_rules:
    state: replaced
    config:
      - afi: ipv4
        rule_sets:
          - name: LOCAL
            description: Example for secshellnet/ansible-vyos-validator
            default_action: drop
            enable_default_log: true
            rules:
              - number: 6
                action: accept
                state:
                  established: true
                  related: true

              - number: 8
                action: accept
                protocol: icmp

              - number: 10
                action: accept
                description: dns
                destination:
                  port: 53
                protocol: udp
