---
- name: "Configure {{ ruleset | replace('_', '-') }} firewall ruleset (ipv4)"
  vyos.vyos.vyos_firewall_rules:
    state: replaced
    config:
      - afi: ipv4
        rule_sets:
          - name: "{{ ruleset | replace('_', '-') }}"
            description: Example for secshellnet/ansible-vyos-validator
            default_action: reject
            enable_default_log: true
            rules: "{{ rules }}"
  vars:
    # merge lists of provided firewall rules (site specific and vlan specific, vlan specific rules are prioritised)
    rules: "{{ [fw_ruleset_vlanxxx.all, fw_ruleset_vlanxxx[ruleset] or [] ]|
               community.general.lists_mergeby('number', recursive=true, list_merge='append_rp') }}"
