---
- name: "Configuration syslog"
  vyos.vyos.vyos_logging_global:
    state: merged
    config:
      hosts:
        - hostname: logging.domain.de
          port: 1514
          facilities:
            - facility: all
              severity: debug
              protocol: udp
